version: '3'

services:
 mobsf:
  image: opensecurity/mobile-security-framework-mobsf:latest
  environment:
   - MOBSF_API_KEY=12345
  ports:
   - 8000:8000

 scan:
  build:
   context: ./scan
  environment:
   - MOBSF_URL=http://mobsf:8000/
   - TARGET_PATH=${TARGET_PATH}
   - DOJOKEY=${DOJOKEY}
   - DOJOIP=${DOJOIP}
   - PRODNAME=${PRODNAME}
  volumes:
   - ./target:/app/target
   - ./output:/app/output
  depends_on:
   - mobsf
